const Tags = {
  TECNOLOGY: "TECNOLOGY",
  SCIENCE: "SCIENCE",
  STUDY: "STUDY",
  HEALTH: "HEALTH",
  EDUCATION: "EDUCATION",
  BUSINESS: "BUSINESS",
  ART: "ART",
  MUSIC: "MUSIC",
  SPORTS: "SPORTS",
  LITERATURE: "LITERATURE",
  HISTORY: "HISTORY",
  TRAVEL: "TRAVEL",
  FOOD: "FOOD",
  ENVIRONMENT: "ENVIRONMENT",
  POLITICS: "POLITICS",
  ECONOMICS: "ECONOMICS",
  PHILOSOPHY: "PHILOSOPHY",
  PSYCHOLOGY: "PSYCHOLOGY",
  TECHNOLOGY: "TECHNOLOGY",
};

module.exports = Tags;
